FunderNest-CapstoneProject/AuctionMVCWeb/Models/UserInfo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AuctionMVCWeb.Models
{
    public class UserInfo
    {
        //Model 
        [Key]
        public int ID { get; set; }
        [Required(ErrorMessage = "First Name is required.")]
        public string FName { get; set; }
        [Required(ErrorMessage = "Last Name is required.")]
        public string LName { get; set; }
        [Required(ErrorMessage = "Email is required.")]
        [RegularExpression(@"^([\w-\.]+)@((\[[0-9]{1,3]\.)|(([\w-]+\.)+))([a-zA-Z{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter valid email.")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Password is required.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Compare("Password", ErrorMessage = "Please re-type your password.")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }



    }
}

FunderNest-CapstoneProject/AuctionMVCWeb/Models/dbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace AuctionMVCWeb.Models
{
    public class dbContext : DbContext
    {
        public DbSet<UserInfo> userInfo { get; set; }

    }
}

FunderNest-CapstoneProject/AuctionMVCWeb/Controllers/DementiaHackathonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Capstone_Project_Prototype.Controllers
{
    public class DementiaHackathonController : Controller
    {

        // GET: TorontoHackathon
        public ActionResult LogIn()
        {
            return View();
        }

        public ActionResult createAccount()
        {
            return View();
        }

        public ActionResult payment()
        {
            return View();
        }

        public ActionResult paymentConfirm()
        {
            return View();
        }


        public ActionResult itemDonation()
        {
            return Redirect("~/AddAuction.aspx");
        }

        public ActionResult itemDonationConfirm()
        {
            return View();
        }

        
        public RedirectResult auction()
        {
            return Redirect("~/Auctions.aspx");
        }
        

        public ActionResult auctionConfirm()
        {
            return View();
        }
    }
}

FunderNest-CapstoneProject/AuctionMVCWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AuctionMVCWeb.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

      
    }
}

FunderNest-CapstoneProject/AuctionMVCWeb/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AuctionMVCWeb.Models;

namespace AuctionMVCWeb.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            using (dbContext db = new dbContext())
            {
                return View(db.userInfo.ToList());
            }
        }

        //Register
        //Get
        public ActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Register(UserInfo info)
        {
           if (ModelState.IsValid)
            {
                using (dbContext db = new dbContext())
                {
                    db.userInfo.Add(info);
                    db.SaveChanges();
                }
                ModelState.Clear();
                ViewBag.Message = info.FName + " " + info.LName + " " + "has successfully registered.";
            }
            return View();
        }

        //Login 
        //Get
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(UserInfo user)
        {
            using (dbContext db = new dbContext())
            {
                var usr = db.userInfo.Where(u => u.Email == user.Email && u.Password == user.Password).FirstOrDefault();
                if (usr != null)
                {
                    Session["ID"] = user.ID.ToString();
                    Session["FName"] = usr.FName.ToString();
                    Session["Email"] = usr.Email.ToString();
                    return RedirectToAction("LoggedIn");
                }
                else
                {
                    ModelState.AddModelError("", "The username or password is incorrect.");
                }
            }
            return View();
        }
        public ActionResult LoggedIn()
        {
            if (Session["Id"] != null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login");
            }
        }
    }
}

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/LogIn.cshtml
@{
    ViewBag.Title = "LogIn";
}
<link rel="stylesheet" type="text/css" href="~/styles/style.css" />

<h1> Toronto Hackathon</h1>
<a href="/DementiaHackathon/createAccount">Create a new account</a>

<h3> Login:</h3>
<form>
   
    Username:<br>
    <input type="text" name="username"><br> <br>

    Password:<br>
    <input type="password" name="password"> <br> <br>

    <input type="submit" class="button" value="Submit" /> <br>

    <br /><button class="forgotpasswd">Forgot Password? </button>

</form> 

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/auction.cshtml
@{
    ViewBag.Title = "auction";
}

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/auctionConfirm.cshtml
@{
    ViewBag.Title = "auctionConfirm";
}

<div id="torontoHackathon"><h1>Dementia Hackathon</h1></div><br /><br />
<div id="title"><h2>Auction Message</h2></div><br /><br />


<p id="msg4">Your Request is being processed!  An email Confirmation of auction item(s) will be sent a day after closing day.  Thank you for your support!</p><br /><br /><br /><br /><br /><br />

<div class="row" id="forget">
    <div class="col-sm-12">
        <button class="btn btn-small btn-success" data-bind='click: submit' onclick="window.location.href='../index.html'">Submit</button>
    </div>
</div>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/createAccount.cshtml
@{
    ViewBag.Title = "createAccount";
}

<link rel="stylesheet" type="text/css" href="~/styles/style.css" />

<h1> Toronto Hackathon</h1>

<h3> Create a new account:</h3>    
 <b>* Please note: The registration fee is $15  </b> <br> <br> 

<form>
   
    First Name:<br>
    <input type="text" name="fname"><br> <br>

    Last Name:<br>
    <input type="text" name="lname"> <br> <br>

    E-mail:<br>
    <input type="email" name="email"> <br> <br>

    <input type="submit" class="button" value="Submit" /> <br>

</form> 

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/itemDonation.cshtml
@{
    ViewBag.Title = "itemDonation";
}

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/itemDonationConfirm.cshtml
@{
    ViewBag.Title = "itemDonationConfirm";
}

<div id="torontoHackathon"><h1>Dementia Hackathon</h1></div><br /><br />
<div id="title"><h2>Item Donation Message</h2></div><br /><br />


<p id="msg4">Details of picking up or sending out donated item(s) will be sent on email.  Please contact us via admin@dementiahackathon.ca if the email is not received upon 2 days.  Thank you for your support!</p><br /><br /><br /><br /><br /><br />

<div class="row" id="forget">
    <div class="col-sm-12">
        <button class="btn btn-small btn-success" data-bind='click: submit' onclick="window.location.href='../index.html'">Submit</button>
    </div>
</div>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/payment.cshtml
@{
    ViewBag.Title = "payment";
}

<div id="torontoHackathon"><h1>Toronto Hackathon</h1></div><br /><br />
<div id="title"><h2>Payment Form</h2></div><br /><br />

<div id="desc"><h3>Please check one of the followings: </h3></div><br />

<div class="row" id="cbox1">
    <div class="col-sm-12">
        <input type="checkbox" value="">
        <label for="cbox1">VISA</label>
    </div>
</div><br />

<div class="row" id="cbox1">
    <div class="col-sm-12">
        <input type="checkbox" value="">
        <label for="cbox1">MasterCard</label>
    </div>
</div><br />

<div class="row" id="cbox1">
    <div class="col-sm-12">
        <input type="checkbox" value="">
        <label for="cbox1">Amex</label>
    </div>
</div><br />

<div class="row">
    <div class="col-sm-6" id="login"><h2>Cardholder Name: </h2></div>
    <div class="col-sm-6">
        <br />
        <input type="text" id="firstname" value="">
    </div>
</div><br />

<div class="row">
    <div class="col-sm-6" id="login"><h2>Card Number: </h2></div>
    <div class="col-sm-6">
        <br />
        <input type="text" id="lastname" value="">
    </div>
</div><br />

<div class="row">
    <div class="col-sm-6" id="login"><h2>Expiry Date: </h2></div>
    <div class="col-sm-6">
        <br />
        <input type="text" id="email" value="">
    </div>
</div><br />

<div class="row">
    <div class="col-sm-6" id="login"><h2>Amount: $</h2></div>
    <div class="col-sm-6">
        <br />
        <input type="text" id="email" value="">
    </div>
</div><br /><br />

<p id="msg2"></p><br /><br />

<div class="row" id="forget">
    <div class="col-sm-12">
        <button class="btn btn-small btn-success" data-bind='click: submit' onclick="window.location.href='paymentConfirm.html'">Submit</button>
    </div>
</div>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/DementiaHackathon/paymentConfirm.cshtml
@{
    ViewBag.Title = "paymentConfirm";
}

<div id="torontoHackathon"><h1>Toronto Hackathon</h1></div><br /><br />
<div id="title"><h2>Payment Confirmation</h2></div><br /><br />


<p id="msg4">Your Payment is processed Successfully!  An email Confirmation is sent!  Thank you for your support!</p><br /><br /><br /><br /><br /><br />

<div class="row" id="forget">
    <div class="col-sm-12">
        <button class="btn btn-small btn-success" data-bind='click: submit' onclick="window.location.href='../index.html'">Submit</button>
    </div>
</div>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>

</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">DementiaHackathon<b class="caret"></b></a>

                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Log In", "Login", "User")</li>
                            <li>@Html.ActionLink("Create Account", "Register", "User")</li>
                            <li>@Html.ActionLink("Payment", "payment", "DementiaHackathon")</li>
                            <li>@Html.ActionLink("Payment Confirmation", "paymentConfirm", "DementiaHackathon")</li>
                            <li>@Html.ActionLink("Dementia Hackathon", "dementiaHackathon", "DementiaHackathon")</li>
                            <li>@Html.ActionLink("Item Donation", "itemDonation", "DementiaHackathon")</li>
                            <li>@Html.ActionLink("Item Donation Message for Confirmation", "itemDonationConfirm", "DementiaHackathon")</li>
                            <li>@Html.ActionLink("Auction", "auction", "DementiaHackathon")</li>
                            <li>@Html.ActionLink("Auction Message for Confirmation", "auctionConfirm", "DementiaHackathon")</li>
                        </ul>
                    </li>
                
                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/User/Index.cshtml
@model IEnumerable<AuctionMVCWeb.Models.UserInfo>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LName)
        </th>

       
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>

    </tr>
}

</table>

FunderNest-CapstoneProject/AuctionMVCWeb/Views/User/LoggedIn.cshtml
@{
    ViewBag.Title = "LoggedIn";
}

@if (Session["Id"] != null)
{
    <h4>Hello @Session["FName"].ToString()</h4>
}

FunderNest-CapstoneProject/AuctionMVCWeb/Views/User/Login.cshtml
@model AuctionMVCWeb.Models.UserInfo

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Login" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FunderNest-CapstoneProject/AuctionMVCWeb/Views/User/Register.cshtml
@model AuctionMVCWeb.Models.UserInfo

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
     @if (ViewBag.Message != null )
     {
         <div class="form-group">
             <div class="col-md-10">@ViewBag.Message</div>
         </div>
     }
        <div class="form-group">
            @Html.LabelFor(model => model.FName, htmlAttributes: new {@class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"> 
            @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}